services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: seplag_backend_api
        restart: always
        working_dir: /var/www/html
        networks:
            - seplagnetwork
        volumes:
            - .:/var/www/html
        depends_on:
            - db
            - minio
        ports:
            - "8000:80"
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/html/public
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=seplag_db
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
        command: >
            sh -c "/usr/local/bin/wait-for-db.sh && apache2-foreground"

    db:
        image: postgres:latest
        container_name: postgres_db
        restart: always
        networks:
            - seplagnetwork
        environment:
            POSTGRES_DB: seplag_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    minio:
        image: minio/minio
        ports:
            - '9000:9000'
            - '9001:9001'
        container_name: minio_storage
        restart: always
        command: server --console-address ":9001" /data
        networks:
            - seplagnetwork
        volumes:
            - 'minio_data:/data'
        environment:
            MINIO_ROOT_USER: 'minioadmin'
            MINIO_ROOT_PASSWORD: 'minioadmin'

    minio-setup:
        image: minio/mc
        depends_on:
            - minio
        networks:
            - seplagnetwork
        entrypoint: >
            /bin/sh -c "
            sleep 10;
            mc alias set myminio http://minio:9000 minioadmin minioadmin &&
            mc mb --ignore-existing myminio/fotos &&
            mc anonymous set none myminio/fotos &&
            exit 0;
            "

networks:
    seplagnetwork:
        driver: bridge

volumes:
    minio_data:
        driver: local
    postgres_data:
        driver: local
